import { Link } from "react-router-dom"
import { Database, Search, Target, SearchCheck, CheckCircle2, FileText, Server } from "lucide-react"
import { Button } from "@/components/ui/button"

export function KnowledgePlatformPage() {
    return (
        <div className="w-full">
            {/* HERO */}
            <section className="container mx-auto px-4 pt-8 pb-24 lg:pt-16 lg:pb-32 relative">

                <div className="max-w-3xl relative z-10 mb-16">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-sm mb-6 text-primary">
                        <Database className="w-4 h-4" /> Enterprise RAG Architecture
                    </div>
                    <h1 className="text-5xl lg:text-7xl font-bold tracking-tight mb-6">
                        Enterprise <span className="text-primary">Knowledge Platform.</span>
                    </h1>
                    <p className="text-xl text-muted-foreground mb-8">
                        Governed search and Q&A powered by Graph-RAG. Absolute clarity with explicit citation chains and RBAC-enforced retrieval.
                    </p>
                    <div className="flex flex-wrap gap-4">
                        <Button asChild size="lg">
                            <Link to="?contact=true">Request a Pilot</Link>
                        </Button>
                        <Button asChild variant="outline" size="lg">
                            <Link to="/security">See Compliance Rules</Link>
                        </Button>
                    </div>
                </div>
            </section>

            {/* WHO IT'S FOR */}
            <section className="bg-white/[0.02] border-y border-white/5 py-16">
                <div className="container mx-auto px-4 text-center max-w-4xl">
                    <h2 className="text-2xl font-semibold mb-8 text-foreground">Engineered for Data-Intensive Teams</h2>
                    <div className="grid md:grid-cols-3 gap-6">
                        <div className="flex flex-col items-center">
                            <Target className="w-8 h-8 text-primary mb-4" />
                            <h3 className="font-bold mb-2">EPCM Providers</h3>
                            <p className="text-sm text-muted-foreground">Navigating tens of thousands of deeply technical standards and municipal codes.</p>
                        </div>
                        <div className="flex flex-col items-center">
                            <FileText className="w-8 h-8 text-primary mb-4" />
                            <h3 className="font-bold mb-2">Project Execution</h3>
                            <p className="text-sm text-muted-foreground">Retrieving critical historical context from past SOWs and RFPs instantaneously.</p>
                        </div>
                        <div className="flex flex-col items-center">
                            <Search className="w-8 h-8 text-primary mb-4" />
                            <h3 className="font-bold mb-2">Regulatory & QA</h3>
                            <p className="text-sm text-muted-foreground">Comparing specifications strictly against required compliance checklists.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* WHAT IT DOES */}
            <section className="container mx-auto px-4 py-24">
                <h2 className="text-3xl font-bold mb-12 text-center">Core Capabilities</h2>
                <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
                    <div className="bg-card glass border border-white/5 p-8 rounded-2xl flex gap-6">
                        <SearchCheck className="w-8 h-8 text-primary shrink-0 lg:w-10 lg:h-10" />
                        <div>
                            <h3 className="text-xl font-bold mb-2">Governed Search & Q&A</h3>
                            <p className="text-muted-foreground text-sm leading-relaxed">Combine hyper-relevant vector similarity search with structured metadata filtering. Retrieve answers grounded exclusively in your private corporate ontology, eliminating hallucinated facts.</p>
                        </div>
                    </div>
                    <div className="bg-card glass border border-white/5 p-8 rounded-2xl flex gap-6">
                        <CheckCircle2 className="w-8 h-8 text-primary shrink-0 lg:w-10 lg:h-10" />
                        <div>
                            <h3 className="text-xl font-bold mb-2">Explicit Citation Chains</h3>
                            <p className="text-muted-foreground text-sm leading-relaxed">Answers are worthless without proof. Every sentence generated by the platform links directly back to the exact source document, page, and paragraph for immediate human verification.</p>
                        </div>
                    </div>
                    <div className="bg-card glass border border-white/5 p-8 rounded-2xl flex gap-6">
                        <Server className="w-8 h-8 text-primary shrink-0 lg:w-10 lg:h-10" />
                        <div>
                            <h3 className="text-xl font-bold mb-2">RBAC Enforced Retrieval</h3>
                            <p className="text-muted-foreground text-sm leading-relaxed">Unlike naive RAG systems, our retrieval engines respect native Active Directory and IAM permissions. Users only retrieve and summarize documents they are explicitly authorized to view.</p>
                        </div>
                    </div>
                    <div className="bg-card glass border border-white/5 p-8 rounded-2xl flex gap-6">
                        <Database className="w-8 h-8 text-primary shrink-0 lg:w-10 lg:h-10" />
                        <div>
                            <h3 className="text-xl font-bold mb-2">Knowledge Graph Enrichment</h3>
                            <p className="text-muted-foreground text-sm leading-relaxed">Documents are mapped dynamically, creating relationships between entities (Organizations, Policies, Parts). The system can traverse interconnected logic, not just keyword matches.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* PROVENANCE AND AUDITABILITY */}
            <section className="py-24 bg-white/[0.02] border-y border-white/5">
                <div className="container mx-auto px-4 text-center max-w-4xl">
                    <h2 className="text-4xl font-bold mb-6 text-foreground">Every answer has a trace.</h2>
                    <p className="text-xl text-muted-foreground mb-12">Retrieval workflows must be forensically sound. We record every chunk of data pulled and the identity of the user requesting it.</p>
                    <div className="p-8 bg-card border border-white/10 rounded-xl font-mono text-sm text-left shadow-2xl glass">
                        <div className="flex gap-4 mb-4 pb-4 border-b border-white/5 text-muted-foreground">
                            <span>[INFO]</span>
                            <span className="text-foreground">REQ_ID: arq_09b4xyz</span>
                            <span>USER: engineer_77</span>
                        </div>
                        <div className="space-y-2 text-primary">
                            <p>&gt; Executing semantic search: "Pressure vessel stress limits per ASME BPVC VIII"</p>
                            <p>&gt; Applying RBAC filter: {`{ group: [engineering_lead, compliance] }`}</p>
                            <p>&gt; Vectors Retrieved: 4 relevant chunks.</p>
                            <p>&gt; Passing context to generation engine...</p>
                            <p className="text-muted-foreground mt-4">&gt; Response logged. Citations mapped to DOC_441_Rev2.pdf</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="py-24 text-center">
                <div className="container mx-auto px-4 max-w-2xl">
                    <h2 className="text-3xl font-bold mb-6">Stop searching. Start verifying.</h2>
                    <p className="text-lg text-muted-foreground mb-8">Discuss ingesting your manuals, standards, and historical data into a secure knowledge graph.</p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <Button asChild size="lg" className="h-14 px-8 text-lg">
                            <Link to="?contact=true">Schedule Technical Sync</Link>
                        </Button>
                    </div>
                </div>
            </section>
        </div>
    )
}
